### ISSUE TITLE
user foo was not found in "/etc/nginx/auth.htpasswd"

### ISSUE THREAD

**Issue by copocaneta** [beevelop/docker-nginx-basic-auth#26]
I am getting this error even though the user exists:

`2020/06/07 08:54:24 [error] 15#15: *12 user "foo" was not found in "/etc/nginx/auth.htpasswd", client: 192.168.0.29, server: , request: "GET / HTTP/1.1", host: "192.168.0.25:8080"`

```
$ docker exec -it xxxxxxxx cat /etc/nginx/auth.htpasswd
'foo:/
```

Why am I getting this "user was not found in" error when the user exists?

**Comment by beevelop** [comment]
Could you share the command you used for launching the container?

**Comment by copocaneta** [comment]
I am running it using docker-compose with the following .yml:

```
version: '3'
services:
 nginxcomauth:
    image: beevelop/nginx-basic-auth
    ports:
    - 8080:80
    environment:
      - HTPASSWD='foo:$$apr1$$odHl5EJN$$KbxMfo86Qdve2FH4owePn.'
      - FORWARD_PORT=9104
      - FORWARD_HOST=127.0.0.1
```
