### ISSUE TITLE
Docker Swarm Support

### ISSUE THREAD

**Issue by tobiasfielitz** [beevelop/docker-nginx-basic-auth#9]
I am trying to use your image in Docker Swarm. Unfortunately I can't get it to work. Accessing localhost:8080 keeps prompting for username and password and the logs of the auth container show: `nginx: [emerg] host not found in upstream "web" in /etc/nginx/conf.d/auth.conf:8`

Here is the docker-compose.yml file I am using:

```
version: '3.4'

services:

  web:
    image: dockercloud/hello-world

  service_auth:
    image: beevelop/nginx-basic-auth
    ports:
      - 8080:80
    environment:
      HTPASSWD: 'foo:$apr1$odHl5EJN$KbxMfo86Qdve2FH4owePn.'
      FORWARD_PORT: 80
      FORWARD_HOST: web```

Started with:

`docker stack deploy -c docker-compose.yml mystack`

**Comment by tobiasfielitz** [comment]
I finally got it working. Here is the compose file:

version: '3.4'

```
services:

  web:
    image: dockercloud/hello-world

  service_auth:
    image: redmarker/nginx-basic-auth
    ports:
      - 8081:80
    depends_on:
      - web
    environment:
      HTPASSWD: 'foo:$$apr1$$odHl5EJN$$KbxMfo86Qdve2FH4owePn.'
      FORWARD_PORT: 80
      FORWARD_HOST: web
```

**$** characters must be escaped with a second $ character in docker-compose.yml.
